import { MetadataRoute } from 'next';

export const dynamic = 'force-static';

export default function sitemap(): MetadataRoute.Sitemap {
    const baseUrl = 'https://bismillahcss.github.io';

    const routes = [
        '',
        '/blog',
        '/blog/introducing-bismillahcss-v1',
        '/blog/building-responsive-layouts',
        '/blog/performance-optimization-tips',
        '/blog/customizing-bismillahcss-themes',
        '/community',
        '/community/showcase',
        '/community/submit-project',
        '/components',
        '/components/buttons',
        '/components/cards',
        '/components/forms',
        '/components/navigation',
        '/components/modals',
        '/components/alerts',
        '/components/tables',
        '/components/tabs',
        '/components/showcase',
        '/components-showcase',
        '/docs',
        '/docs/components',
        '/docs/components/buttons',
        '/docs/components/cards',
        '/docs/components/forms',
        '/docs/components/modals',
        '/docs/configuration',
        '/docs/customization/configuration',
        '/docs/customization/extending',
        '/docs/customization/plugins',
        '/docs/customization/theming',
        '/docs/dark-mode',
        '/docs/installation',
        '/docs/pseudo-classes',
        '/docs/quick-start',
        '/docs/responsive-design',
        '/docs/utility-classes',
        '/docs/utility-classes/colors',
        '/docs/utility-classes/flexbox',
        '/docs/utility-classes/grid',
        '/docs/utility-classes/layout',
        '/docs/utility-classes/spacing',
        '/docs/utility-classes/typography',
        '/docs/utility-first',
        '/playground',
        '/bismillah-utilities',
        '/components/buttons.html',
        '/components/cards.html',
        '/components/forms.html',
        '/components/navbar.html',
        '/components/modals.html',
        '/components/alerts.html',
        '/components/tables.html',
        '/components/tabs.html',
        '/components/characters.html',
        '/components/typography.html',
        '/components/utilities.html',
        '/components/layout.html',
        '/blog/redefining-styling-intent-driven-css',
        '/privacy',
        '/terms',
        '/license',
        '/showcase',
        '/docs/ultra/moving-border',
        '/docs/ultra/spotlight',
        '/docs/ultra/glare-card',
    ];

    return routes.map((route) => ({
        url: `${baseUrl}${route}`,
        lastModified: new Date(),
        changeFrequency: 'weekly',
        priority: route === '' ? 1 : 0.8,
    }));
}
